guard 'compass' do
  watch(%r{^src/(.*)\.s[ac]ss})
end

# # Alternative
# guard 'compass', :workdir => 'not_current_dir', :configuration_file => 'path/to/my/compass_config.rb' do
#   watch(%r{^src/(.*)\.s[ac]ss})
# end
