guard 'compass' do
  watch('^src/(.*)\.s[ac]ss')
end

# # Alternative
# guard 'compass', :workdir => 'not_current_dir', :configuration_file => 'path/to/my/compass_config.rb' do
#   watch('^src/(.*)\.s[ac]ss')
# end
